spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone:  GMT+8
  datasource:
    url: jdbc:mysql://192.168.3.109:3306/manager?user=root&password=root&useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /manager
  port: 8081
logging:
  level:
    com.googlecode.jsonrpc4j: debug
